name: Build and Deploy to Azure

on:
  push:
    branches:
      - test-workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registery
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: pazmichael.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Build and Push Docker image to ACR
      - name: Build and Push Docker Image to ACR
        run: |
          docker build . -t pazmichael.azurecr.io/fastapi-analytics-app:latest
          docker push pazmichael.azurecr.io/fastapi-analytics-app:latest

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fastapi-analytics-webapp
          slot-name: production
          images: pazmichael.azurecr.io/fastapi-analytics-app:latest
