name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login pazmichael.azurecr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t pazmichael.azurecr.io/fastapi-analytics-app:latest .
          docker push pazmichael.azurecr.io/fastapi-analytics-app:latest

      # Deploy the Docker image to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fastapi-analytics-webapp
          slot-name: production
          images: pazmichael.azurecr.io/fastapi-analytics-app:latest
